### PR TITLE
add warning about long npm install command

### PR DESCRIPTION
**Pull request by bassjacob**

### CODE REVIEW

**Comment by jordwalke** [comment]
What did you experience? Which part of the install was slow for you?

**Comment by bassjacob** [comment]
I'm pretty sure it was the install of esy. It's not actually much slower than I would expect, but npm gives no visual feedback when installing from git, it just spins and looks like its frozen or failed or something.

It's been a visual feedback issue for a few people I've helped install, not so much a length of install time issue.

**Comment by jordwalke** [comment]
@bassjacob Were they binary installs? Binary installs don't install esy at all. They merely install the result of a build. Only `dev` builds install esy.

**Comment by bassjacob** [comment]
Ah, was still looking at master, not the binary tag. Perfect, if we're moving away from installing esy then we can just ignore this 😄

**Comment by jordwalke** [comment]
`esy` is just a tool that helps us package up opam packages on npm, and by the time you even get an npm package, esy has deleted itself. (The exception is `dev` packages which go through the whole process - most people don't install those)

**Pull request closed without merging**
